# **2.7_更多数组**

### 一、针对NumPy数组的常用操作

#### (一)、用concatenate函数连接数组

1. concatenate函数接收的参数是列表，所以可以把两个数组，用中括号包围起来，作为一个列表传进去

2. concatenate函数输出的结果，是两个数组里所有元素拼接起来后组成的新数组

In [2]:
import numpy as np

arr1 = np.array([5, 17, 3, 26, 31])
arr2 = np.zeros(2)
np.concatenate([arr1, arr2])

array([ 5., 17.,  3., 26., 31.,  0.,  0.])

**可以看到数组里的数字后面都有个小数点，这是因为zeroes方法产生的是浮点数类型的数组，然后数组里数据类型又必须统一，所以拼接后的结果也是浮点数数组**

3. 由于传入列表的长度是不限的，所以也可以一次性拼接多个数组
   ```python
   np.concatenate([arr1, arr2, arr3])
   ```

#### (二)、对内容进行排序

1. 针对列表来说
   
    1）sorted函数
   
   传入列表后，就会返回一个新的排序好的列表
   
   **只返回排序好的新列表，不改变原始列表**

   **也可以传入Series作为参数**
   
    2）sort方法
   
   调用后，该列表里面的元素就都会被排序好
   
   **什么都不返回，但原始列表会被排序好**

In [8]:
list1 = [5, 17, 3, 26, 31]
sorted_list1 = sorted(list1)
print(sorted_list1)
print(list1)

print(list1.sort())
print(list1)

[3, 5, 17, 26, 31]
[5, 17, 3, 26, 31]
None
[3, 5, 17, 26, 31]


2. 针对NumPy数组来说

    1）NumPy的sort函数

    np.sort会返回排序好的新的数组，但是传入的原始数组不会被改变

   **也可以传入Series作为参数**

    2）NumPy的sort方法

    而数组的sort方法，会直接在该数组上进行改动，把元素排序好
   
    **你可以根据是否要直接更改数组，决定使用**

In [9]:
arr1 = np.array([5, 17, 3, 26, 31])
print(np.sort(arr1))
print(arr1)

print(arr1.sort())
print(arr1)

[ 3  5 17 26 31]
[ 5 17  3 26 31]
None
[ 3  5 17 26 31]


#### (三)、用索引获得元素

1. 获得某个元素

   1）正着数

    第一个元素的索引为0，后面依次+1

   2）倒着数

   最后一个元素的索引是-1，倒数第二个的索引是-2，以此类推

2. 获得某范围的多个元素

   切片会返回开头索引到结束索引前一个的所有元素

In [11]:
arr1[1: 4]

array([ 5, 17, 26])

#### (四)、数组和数组进行运算

**NumPy数组的强项之一是运算**

1. 加减乘除

   1)数组与数组之间

   如果把形状相同的两个一维数组进行运算，会返回一个相同位置元素加减乘除后得到的数组。而列表做不到这么便捷了

In [15]:
arr4 = np.array([6, 7, 8, 9, 10])
arr5 = np.array([2, 2, 2, 2, 2])
print(arr4 + arr5)
print(arr4 - arr5)
print(arr4 * arr5)
print(arr4 / arr5)

[ 8  9 10 11 12]
[4 5 6 7 8]
[12 14 16 18 20]
[3.  3.5 4.  4.5 5. ]


    2）数组和单个数字之间

    如果学过线性代数，可以看成是向量和标量之间的运算

In [29]:
arr4 * 3

array([18, 21, 24, 27, 30])

    这个例子里的乘3会运用在数组的每一个数字上，这种操作机制，叫做广播机制

    3）聚合运算

    a.聚合运算是指，通过一组值，来得到一个值

    b.包括max求最大值，min求最小值，sum求和，mean求平均值等待

    c.数组.操作名()，返回相应的运算结果

In [17]:
print(arr4.max())
print(arr4.min())
print(arr4.sum())
print(arr4.mean())

10
6
40
8.0


#### (五)、根据条件筛选数组元素

In [27]:
arr = np.array([-22, 3, 65, 9, 11, 7])
arr > 6

array([False, False,  True,  True,  True,  True])

1. 

一个数组和一个数字之间的操作，根据广播机制，> 6会被运用到每一个数字上，那产生的结果就是由True和False组成的布尔值数组，每个布尔值都代表了这个数字是否大于6

In [28]:
arr[arr > 6]

array([65,  9, 11,  7])

布尔值数组可以用来对形状相同的数组进行索引，在方括号里放上这个布尔值数组，相应位置为True的元素就会被筛选出来，那作为结果的数组里就会有那个元素

2. 结合逻辑运算，让筛选逻辑更加复杂

与：Python里用and，在数组上用&

或：Python里用or，在数组上用|

非：Python里用not，在数组上用~

In [22]:
arr[(arr > 6) & (arr < 10)]

array([9, 7])

比如要筛选出所有大于6且小于10的数字，就把 > 6和 < 10这两个条件用括号括住，表示这两个条件要先于&计算

### 二、其他

1. np.nan表示缺失值，将np.nan赋值给其他变量，可以使变量为NaN值

In [5]:
np.nan

nan